// Knowledge-synthesis engine.
// Produces a complete, structured exploration brief by fusing every wired data
// stream: ranked engine targets, regional intelligence (USGS/NASA/NOAA/IRIS/
// Open-Meteo/tectonics/prices/deposits), the deep geological knowledge base
// (geobotany, P-T regimes, pathfinders, structure, surface expressions), the
// remote-sensing method stack, and any user-uploaded documents.
//
// This is what runs when no external LLM key is configured: a real expert
// synthesis rather than a placeholder. When keys exist, this brief is also fed
// to the models as grounding context.

import { knowledgeFor } from "./knowledge.js";
import { activeMethods, availableToAdd } from "./remote-methods.js";

function pct(x) {
  return `${Math.round((x || 0) * 100)}%`;
}

function bullet(lines) {
  return lines.filter(Boolean).map((l) => `- ${l}`).join("\n");
}

function targetTable(targets) {
  return targets
    .map(
      (t) =>
        `${t.id} | Priority ${t.tier} | ${pct(t.confidence)} | ${t.lat.toFixed(4)}, ${t.lng.toFixed(4)} | halo ~${t.radiusKm} km`,
    )
    .join("\n");
}

function summariseIntel(intel) {
  if (!intel) return null;
  const out = [];
  const mrds = intel.usgs?.mineralDeposits?.count || 0;
  if (mrds) {
    const names = (intel.deposits?.mrdsNearby || []).slice(0, 4).map((d) => `${d.name} (${d.commodity}, ${d.distanceKm} km)`);
    out.push(`USGS MRDS records ${mrds} known occurrence(s) in range: ${names.join("; ") || "see list"}. Proximity to documented mineralisation raises confidence.`);
  } else {
    out.push("No USGS MRDS occurrence within the search radius. A blank database often means under-explored ground, not barren ground.");
  }
  const irisN = intel.seismic?.iris?.count || 0;
  const usgsEq = intel.usgs?.earthquakes?.count || 0;
  if (irisN || usgsEq) {
    out.push(`Seismicity: ${irisN} IRIS and ${usgsEq} USGS events nearby - active crustal structures can act as fluid pathways and indicate live tectonic plumbing.`);
  }
  const tb = intel.tectonics?.nearestBoundary;
  if (tb) {
    out.push(`Nearest plate boundary (${tb.plateBoundary}) is ~${tb.distanceKm} km away${intel.tectonics.inRiftZone ? " - within a rift-influenced zone favourable for deep magmatism and geothermal flux." : "."}`);
  }
  const mag = intel.noaa?.magnetic;
  if (mag) {
    out.push(`Regional magnetic field ${mag.totalFieldN} nT (declination ${mag.declinationDeg}deg) provides the baseline for detecting magnetite-bearing intrusions and demagnetised alteration shears.`);
  }
  const om = intel.openMeteo;
  if (om && om.soilTemp) {
    out.push(`Terrain ${om.elevationM} m elevation; soil thermal gradient ${om.soilTemp.surface0cm}degC (surface) to ${om.soilTemp.deep54cm}degC (54 cm) for hydrothermal and moisture screening.`);
  }
  const price = intel.commodities?.spotPrices;
  if (price?.prices?.length) {
    const p0 = price.prices[0];
    out.push(`Live commodity pricing available (${price.source}); current reference: ${p0.name || p0.metal} ${typeof p0.usd === "number" ? "$" + p0.usd.toFixed(2) : p0.usd}.`);
  }
  const demand = intel.commodities?.demandForecast;
  if (demand?.demandIndex) {
    const di = demand.demandIndex;
    out.push(`Demand outlook (${demand.commodity}): index ${di["2024"]} (2024) rising to ${di["2040"]} (2040). ${intel.commodities.supplyChain || ""}`);
  }
  return out;
}

function geobotanySection(knowledge) {
  const lines = [];
  if (knowledge.geobotany) {
    for (const g of knowledge.geobotany) {
      lines.push(`${g.species} (${g.common}): ${g.note}`);
    }
  }
  if (knowledge.acidStress) {
    for (const g of knowledge.acidStress) lines.push(`${g.common}: ${g.note}`);
  }
  return lines;
}

/**
 * Build the full brief. Returns { brief, sections } where brief is the
 * complete text and sections is a structured object for the stage views.
 */
export function buildSynthesis({ engineResult, intel, aoiLabel, documents = [] }) {
  const c = engineResult.commodity;
  const targets = engineResult.targets || [];
  const knowledge = knowledgeFor(c.id);
  const intelLines = summariseIntel(intel) || [];
  const geobotany = geobotanySection(knowledge);
  const top = targets[0];

  const exec = [
    `${c.name} prospectivity assessment for ${aoiLabel || "the selected area"}.`,
    `${targets.length} ranked target(s) were generated by fusing structural, geophysical, geochemical, spectral and subsurface signals; ${targets.filter((t) => t.tier === "A").length} reached priority tier A.`,
    top ? `The lead target ${top.id} (${pct(top.confidence)} confidence) at ${top.lat.toFixed(4)}, ${top.lng.toFixed(4)} should be progressed first.` : "",
  ].filter(Boolean).join(" ");

  const sections = {};

  sections.executiveSummary = exec;

  sections.rankedTargets = targets.length
    ? `ID | Priority | Confidence | Coordinates | Search halo\n${targetTable(targets)}`
    : "No targets above threshold in this area at the current detail setting.";

  sections.depositModel = bullet([
    `Deposit model: ${c.depositModel || "structurally controlled mineralisation"}.`,
    knowledge.structure ? `Structural control: ${knowledge.structure}` : null,
    knowledge.pt ? `Pressure-temperature window: ${knowledge.pt.facies}, ${knowledge.pt.depthKm}, ${knowledge.pt.tempC} degC. ${knowledge.pt.note}` : null,
    knowledge.pathfinders ? `Pathfinder halo: ${knowledge.pathfinders}` : null,
  ]);

  sections.classicIndicators = bullet([
    geobotany.length ? `Geobotanical indicators to map (biogeochemical halo):` : "Geobotanical stress mapping over acidic / metalliferous soils.",
    ...geobotany,
    `Surface expressions to walk for: ${Object.values(knowledge.surfaceExpressions).slice(0, 4).join(" ")}`,
  ]);

  sections.regionalIntelligence = intelLines.length
    ? bullet(intelLines)
    : "Regional intelligence feeds returned no anomalies in range; treat as frontier ground.";

  const active = activeMethods().map((m) => `${m.name}: ${m.finds}`);
  const toAdd = availableToAdd().slice(0, 5).map((m) => `${m.name} (${m.penetrates})`);
  sections.sensingPlan = [
    "Active non-invasive layers in this assessment:",
    bullet(active),
    "",
    "Recommended additional free space-based methods to confirm before drilling:",
    bullet(toAdd),
  ].join("\n");

  if (documents.length) {
    sections.userDocuments = bullet(
      documents.map((d) => `${d.name}: ${d.summary || (d.excerpt ? d.excerpt.slice(0, 180) : "uploaded")}`),
    );
  }

  sections.fieldProgram = bullet([
    top ? `Stage 1: ground-truth ${top.id} with an indicator-species walkover and portable XRF soil traverse across the modelled halo.` : "Stage 1: reconnaissance mapping over the highest-ranked cells.",
    "Stage 2: orientation soil/stream-sediment geochemistry on the pathfinder suite; confirm spectral and biogeochemical anomalies.",
    "Stage 3: ground geophysics (magnetics + IP/resistivity or gravity) over confirmed geochemical anomalies to define drill collars.",
    "Stage 4: scout drilling on coincident anomalies; feed every hole (including misses) back into the model to sharpen the next iteration.",
  ]);

  sections.riskCaveat =
    "Confidence values are model-derived prospectivity from remote and regional data, not verified resource. No space-based method confirms an ore body at depth; final proof requires ground geophysics and drilling. Use this brief to prioritise fieldwork.";

  const brief = [
    `# ${c.name} Exploration Brief`,
    `Area: ${aoiLabel || "selected AOI"}`,
    "",
    "## Executive summary",
    sections.executiveSummary,
    "",
    "## Ranked targets",
    sections.rankedTargets,
    "",
    "## Deposit model and controls",
    sections.depositModel,
    "",
    "## Classic and biogeochemical indicators",
    sections.classicIndicators,
    "",
    "## Regional intelligence",
    sections.regionalIntelligence,
    "",
    "## Non-invasive sensing plan",
    sections.sensingPlan,
    documents.length ? "\n## Operator documents considered\n" + sections.userDocuments : "",
    "",
    "## Recommended field program",
    sections.fieldProgram,
    "",
    "## Risk and confidence",
    sections.riskCaveat,
  ]
    .filter((s) => s !== "")
    .join("\n");

  return { brief, sections };
}
